"""Migratation

Revision ID: c0dc24a97dda
Revises: 
Create Date: 2022-07-29 03:48:40.686634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0dc24a97dda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
